---

# Ansible playbook to set up the conductor.

# Install MonetDB
# On the conductor node, we use MonetDBLite, just for a bit more fun
- hosts: conductor
  tasks:

  # To install MonetDBLite we need pip3, and Ansible needs setuptools
  - name: Install additional Python packages
    become: yes
    apt:
      name: ['python3-pip', 'python3-dev', 'python3-setuptools']
      state: present

  - name: Install MonetDBLite
    pip:
      name: monetdblite
      executable: pip3
